# Regressão Linear Simples

In [3]:
#!pip install plotly --upgrade

In [12]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns 
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

## Base plano saúde

In [7]:
base_plano_saude = pd.read_csv('plano_saude.csv')
print(base_plano_saude.shape)
base_plano_saude.head()

(10, 2)


idade  custo
0     18    871
1     23   1132
2     28   1242
3     33   1356
4     38   1488

In [9]:
X_saude = base_plano_saude.iloc[:,0].values
y_saude = base_plano_saude.iloc[:,1].values
X_saude.shape, y_saude.shape

((10,), (10,))

In [10]:
np.corrcoef(X_saude, y_saude)  # correlação perfeita, pois valores são iguais

array([[1.        , 0.93091958],
       [0.93091958, 1.        ]])

Correlação forte indica que regressão linear pode funcionar!

In [11]:
X_saude = X_saude.reshape(-1, 1)
y_saude = y_saude.reshape(-1, 1)
X_saude.shape, y_saude.shape

((10, 1), (10, 1))

In [13]:
regressor_saude = LinearRegression()
regressor_saude.fit(X_saude, y_saude)

LinearRegression()

In [15]:
# b0
regressor_saude.intercept_

array([-558.94909091])

In [16]:
# b1
regressor_saude.coef_

array([[61.86787879]])

In [18]:
previsoes = regressor_saude.predict(X_saude)
previsoes.shape

(10, 1)

In [24]:
grafico = px.scatter(x = X_saude.ravel(), y = y_saude.ravel())
grafico.add_scatter(x = X_saude.ravel(), y = previsoes.ravel())
grafico.show()