# Outros tipos de regressão

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns 
import matplotlib.pyplot as plt

In [61]:
from sklearn.linear_model import LinearRegression
from yellowbrick.regressor import ResidualsPlot
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Regressão Polinomial

## Base Plano de Saúde - 2

In [3]:
base_plano_saude = pd.read_csv('plano_saude2.csv')
print(base_plano_saude.shape)
base_plano_saude.head()

(10, 2)


idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150

In [4]:
X_saude = base_plano_saude.iloc[:,0].values.reshape(-1,1)
y_saude = base_plano_saude.iloc[:,1].values.reshape(-1,1)
X_saude.shape, y_saude.shape

((10, 1), (10, 1))

In [5]:
poly = PolynomialFeatures(degree=4)
X_saude_poly = poly.fit_transform(X_saude)
X_saude_poly.shape

(10, 5)

In [6]:
regressor_saude_poly = LinearRegression()
regressor_saude_poly.fit(X_saude_poly, y_saude)

LinearRegression()

In [7]:
# b0, b1, b2, b3, b4, b5
regressor_saude_poly.intercept_, regressor_saude_poly.coef_ 

(array([16561.97465354]),
 array([[ 0.00000000e+00, -2.12242253e+03,  9.90404200e+01,
         -1.95058276e+00,  1.40792541e-02]]))

In [8]:
novo = [[40]]
novo = poly.transform(novo)
regressor_saude_poly.predict(novo)

array([[1335.33958151]])

In [9]:
previsoes = regressor_saude_poly.predict(X_saude_poly)
previsoes.shape

(10, 1)

In [26]:
grafico = px.scatter(x=X_saude[:,0], y=y_saude.ravel())
grafico.add_scatter(x=X_saude[:,0], y=previsoes.ravel(), name='Regressão')
grafico.show()

## Base Preço Casas

In [45]:
base_preco_casas = pd.read_csv('house_prices.csv')
print(base_preco_casas.shape)
base_preco_casas.head()

(21613, 21)


id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [51]:
X_casas = base_preco_casas.iloc[:,3:19].values
y_casas = base_preco_casas.iloc[:,2].values
X_casas.shape, y_casas.shape

((21613, 16), (21613,))

In [52]:
X_casas_train, X_casas_test, y_casas_train, y_casas_test = train_test_split(X_casas, y_casas, test_size=0.3, random_state=0)
print(f'Treino: X-->{X_casas_train.shape} e y-->{y_casas_train.shape}')
print(f'Teste:  X-->{X_casas_test.shape}  e y-->{y_casas_test.shape}')

Treino: X-->(15129, 16) e y-->(15129,)
Teste:  X-->(6484, 16)  e y-->(6484,)


In [53]:
poly = PolynomialFeatures(degree=2)
X_casas_train_poly = poly.fit_transform(X_casas_train)
X_casas_test_poly = poly.fit_transform(X_casas_test)
X_casas_train_poly.shape, X_casas_test_poly.shape

((15129, 153), (6484, 153))

In [54]:
regressor_casa_poly = LinearRegression()
regressor_casa_poly.fit(X_casas_train_poly, y_casas_train)

LinearRegression()

In [57]:
# train
regressor_casa_poly.score(X_casas_train_poly, y_casas_train)

0.8179300770822937

In [56]:
# test
regressor_casa_poly.score(X_casas_test_poly, y_casas_test)

0.8153204842188788

In [60]:
previsoes = regressor_casa_poly.predict(X_casas_test_poly)
previsoes.shape

(6484,)

In [62]:
# MAE
mean_absolute_error(y_casas_test, previsoes)

101236.4104077141