# Outros tipos de regressão

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns 
import matplotlib.pyplot as plt

In [25]:
from sklearn.linear_model import LinearRegression
from yellowbrick.regressor import ResidualsPlot
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures

# Regressão Polinomial

## Base Plano de Saúde - 2

In [20]:
base_plano_saude = pd.read_csv('plano_saude2.csv')
print(base_plano_saude.shape)
base_plano_saude.head()

(10, 2)


idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150

In [21]:
X_saude = base_plano_saude.iloc[:,0].values.reshape(-1,1)
y_saude = base_plano_saude.iloc[:,1].values.reshape(-1,1)
X_saude.shape, y_saude.shape

((10, 1), (10, 1))

In [33]:
poly = PolynomialFeatures(degree=4)
X_saude_poly = poly.fit_transform(X_saude)
X_saude_poly.shape

(10, 5)

In [34]:
regressor_saude_poly = LinearRegression()
regressor_saude_poly.fit(X_saude_poly, y_saude)

LinearRegression()

In [35]:
# b0, b1, b2, b3, b4, b5
regressor_saude_poly.intercept_, regressor_saude_poly.coef_ 

(array([16561.97465354]),
 array([[ 0.00000000e+00, -2.12242253e+03,  9.90404200e+01,
         -1.95058276e+00,  1.40792541e-02]]))

In [37]:
novo = [[40]]
novo = poly.transform(novo)
regressor_saude_poly.predict(novo)

array([[1335.33958151]])

In [38]:
previsoes = regressor_saude_poly.predict(X_saude_poly)
previsoes.shape

(10, 1)