# Amostragem

In [85]:
import pandas as pd
import numpy as np
import random

from sklearn.model_selection import StratifiedShuffleSplit

In [5]:
base_census = pd.read_csv('Bases de dados/census.csv')
print(base_census.shape)
base_census.head()

(32561, 15)


age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [12]:
print(base_census.info())
base_census.describe(include='all').T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   final-weight    32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loos    32561 non-null  int64 
 12  hour-per-week   32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None


count unique                  top   freq     mean      std  \
age             32561    NaN                  NaN    NaN  38.5816  13.6404   
workclass       32561      9              Private  22696      NaN      NaN   
final-weight    32561    NaN                  NaN    NaN   189778   105550   
education       32561     16              HS-grad  10501      NaN      NaN   
education-num   32561    NaN                  NaN    NaN  10.0807  2.57272   
marital-status  32561      7   Married-civ-spouse  14976      NaN      NaN   
occupation      32561     15       Prof-specialty   4140      NaN      NaN   
relationship    32561      6              Husband  13193      NaN      NaN   
race            32561      5                White  27816      NaN      NaN   
sex             32561      2                 Male  21790      NaN      NaN   
capital-gain    32561    NaN                  NaN    NaN  1077.65  7385.29   
capital-loos    32561    NaN                  NaN    NaN  87.3038   402.96   
hour-per-week   32561    NaN                  NaN    NaN  40.4375  12.3474   
native-country  32561     42        United-States  29170      NaN      NaN   
income          32561      2                <=50K  24720      NaN      NaN   

                  min     25%     50%     75%          max  
age                17      28      37      48           90  
workclass         NaN     NaN     NaN     NaN          NaN  
final-weight    12285  117827  178356  237051  1.48470e+06  
education         NaN     NaN     NaN     NaN          NaN  
education-num       1       9      10      12           16  
marital-status    NaN     NaN     NaN     NaN          NaN  
occupation        NaN     NaN     NaN     NaN          NaN  
relationship      NaN     NaN     NaN     NaN          NaN  
race              NaN     NaN     NaN     NaN          NaN  
sex               NaN     NaN     NaN     NaN          NaN  
capital-gain        0       0       0       0        99999  
capital-loos        0       0       0       0         4356  
hour-per-week       1      40      40      45           99  
native-country    NaN     NaN     NaN     NaN          NaN  
income            NaN     NaN     NaN     NaN          NaN

## Amostragem aleatória simples

In [21]:
df_amostra_aleat_simples = base_census.sample(n=100, replace=False, random_state=1)  # replace permite que o mesmo registro nao seja selecionado mais de uma vez (já pe dado como False)
print(df_amostra_aleat_simples.shape)   # 100 registros completos da base
#list(df_amostra_aleat_simples.index)

(100, 15)


In [22]:
def amostragem_aleat_simples(dataset, amostras):
    return dataset.sample(n=amostras)

In [26]:
df_teste = amostragem_aleat_simples(base_census, 2)
df_teste

age workclass  final-weight      education  education-num  \
28199   25   Private        231714   Some-college             10   
17179   44   Private         99651        Masters             14   

            marital-status          occupation relationship    race    sex  \
28199   Married-civ-spouse   Machine-op-inspct      Husband   White   Male   
17179   Married-civ-spouse     Exec-managerial      Husband   White   Male   

       capital-gain  capital-loos  hour-per-week  native-country  income  
28199             0             0             40   United-States   <=50K  
17179          5178             0             40   United-States    >50K

## Amostragem sistemática

In [27]:
base_census.shape

(32561, 15)

In [31]:
# amostra de 100 pessoas
len(base_census) // 100

# selecionar um número aleatório entre 0 e 325
# o próximo será do número escolhido até o numero + 325

325

In [38]:
random.seed(1)  # retornar sempre o mesmo
random.randint(0, 325)

68

In [40]:
print(68 + 325)
random.seed(1)  
random.randint(68, 68+325)

393


136

Com a biblioteca numpy:

In [43]:
np.arange(68, len(base_census), step=325)  # retorna 100 numeros

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [48]:
def amostragem_sistematica(dataset, amostras):
    intervalo = len(dataset) // amostras
    random.seed(1)
    inicio = random.randint(0, intervalo)
    indices = np.arange(inicio, len(dataset), step=intervalo)
    amostra_sist = dataset.iloc[indices]
    return amostra_sist

In [50]:
df_teste = amostragem_sistematica(base_census, 100)
df_teste.shape

(100, 15)

## Amostragem por Grupos

Define-se um numero de grupos e pega-se registros de cada grupo (aleatoriamente)

In [54]:
len(base_census) / 10  # numero de pessoas por grupo

3256.1

In [56]:
grupos = []
id_grupo = 0
contagem = 0

for _ in base_census.iterrows():
    grupos.append(id_grupo)
    contagem +=1
    if contagem > (len(base_census) // 10):
        contagem = 0
        id_grupo +=1

In [58]:
len(grupos)  # para cada registro

32561

In [63]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248],
       dtype=int64))

In [65]:
base_census['grupo'] = grupos
base_census.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
0          2174             0             40   United-States   <=50K      0  
1             0             0             13   United-States   <=50K      0  
2             0             0             40   United-States   <=50K      0  
3             0             0             40   United-States   <=50K      0  
4             0             0             40            Cuba   <=50K      0

In [70]:
random.randint(0, 9)  # escolhendo o grupo

1

In [71]:
df_agrupamento = base_census[base_census['grupo']==1]
df_agrupamento.shape

(3257, 16)

In [78]:
def amostragem_agrup(dataset, numero_grupos):
    intervalo = len(dataset) / numero_grupos
    grupos = []
    id_grupo = 0
    contagem = 0

    for _ in dataset.iterrows():
        grupos.append(id_grupo)
        contagem +=1
        if contagem > intervalo:
            contagem = 0
            id_grupo +=1
    
    dataset['grupo'] = grupos
    random.seed(1)
    grupo_selecionado = random.randint(0, numero_grupos)
    return dataset[dataset['grupo'] == grupo_selecionado]

In [80]:
df_teste = amostragem_agrup(base_census, 100)
df_teste.shape

(326, 16)

In [83]:
df_teste['grupo'].value_counts()

17    326
Name: grupo, dtype: int64

## Amostragem estratificada

In [87]:
base_census['income'].value_counts(normalize=True)

 <=50K    0.75919
 >50K     0.24081
Name: income, dtype: float64

In [90]:
split = StratifiedShuffleSplit(test_size=0.1)
for x, y in split.split(base_census, base_census['income']):
    df_x = base_census.iloc[x]
    df_y = base_census.iloc[y]

In [91]:
df_x.shape, df_y.shape # 90% e 10% da base de dados

((29304, 16), (3257, 16))

In [93]:
df_x['income'].value_counts(normalize=True)

 <=50K    0.75918
 >50K     0.24082
Name: income, dtype: float64

## Amostragem de reservatório

- Data stream
- Teste validado

In [96]:
stream = [i for i in range(len(base_census))]
    
#print(stream)

In [119]:
def amostragem_reservatorio(dataset, amostras):
    stream = [i for i in range(len(dataset))]
    tamanho = len(dataset)
    i = 0
    
    reservatorio = [0] * amostras
    for i in range(amostras):
        reservatorio[i] = stream[i]
    
    while i < tamanho:
        j = random.randrange(i+1)
        if j < amostras:
            reservatorio[j] = stream[i]
        i +=1
        
    return dataset.iloc[reservatorio]

In [120]:
df_teste = amostragem_reservatorio(base_census, 100)
print(df_teste.shape)
df_teste.head()

(100, 16)


age workclass  final-weight      education  education-num  \
14073   54   Private        257869   Some-college             10   
14143   28   Private        190525      Bachelors             13   
5878    28   Private         65389        HS-grad              9   
3258    19   Private        417657        HS-grad              9   
4552    51   Private         55507        HS-grad              9   

            marital-status          occupation    relationship  \
14073            Separated       Other-service   Not-in-family   
14143   Married-civ-spouse     Exec-managerial         Husband   
5878         Never-married       Other-service   Not-in-family   
3258         Never-married   Handlers-cleaners       Own-child   
4552    Married-civ-spouse        Craft-repair         Husband   

                      race    sex  capital-gain  capital-loos  hour-per-week  \
14073                White   Male             0             0             28   
14143                White   Male             0             0             46   
5878    Amer-Indian-Eskimo   Male             0             0             30   
3258                 White   Male             0             0             50   
4552                 Black   Male             0             0             40   

       native-country  income  grupo  
14073        Columbia   <=50K     43  
14143   United-States    >50K     43  
5878    United-States   <=50K     18  
3258    United-States   <=50K      9  
4552    United-States   <=50K     13